openapi: 3.0.0
info:
  title: fiap-x-app API
  description: API documentation for fiap-x-app
  version: 1.0.0
paths:
  /auth/login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: example@mail.com
                password:
                  type: string
                  example: 1234
      responses:
        '200':
          description: Successful login
  /videos:
    get:
      summary: Get videos
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of videos
  /videos/{id}:
    get:
      summary: Get video by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Video details
  /videos/upload:
    post:
      summary: Upload video
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Video uploaded
  /videos/{id}/download/images:
    get:
      summary: Download video images
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Downloaded images
  /user:
    post:
      summary: Create user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: example@mail.com
                password:
                  type: string
                  example: 1234
      responses:
        '200':
          description: User created
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
